<a href="https://colab.research.google.com/github/muhammad-28/ICT-internship-ML-AI/blob/numpy-and-pandas/Day2_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]

sum1=list1+list2


sum1

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
sum_1=[]

for num1,num2 in zip(list1,list2):
  sum_1.append(num1+num2)

sum_1  

[6, 8, 10, 12]

Numpy

In [ ]:
import numpy as np

arr1=np.array(list1)

arr1

array([1, 2, 3, 4])

In [ ]:
arr2=np.array(list2)

arr2

array([5, 6, 7, 8])

In [ ]:
sum_l1=arr1+arr2

sum_l1

array([ 6,  8, 10, 12])

In [ ]:
type(arr1)


numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
list3=[[1,12,5,3],[9,4,5,6]]

arr3=np.array(list3)

arr3.ndim

2

In [ ]:
arr3.shape

(2, 4)

In [ ]:
arr4=np.arange(8)

arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr5=arr4.reshape(2,4)

arr5

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr4.mean()

3.5

In [ ]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,4)

array([[0.61248037, 0.0443179 , 0.32793218, 0.68608844],
       [0.13620793, 0.52549757, 0.69939066, 0.62249875],
       [0.89753415, 0.68479383, 0.92886907, 0.21949809]])

**Pandas**

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/auto-mpg.csv')